In [2]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_iris 

In [3]:
iris = load_iris()
x = iris.data 
y = iris.target 

In [4]:
# splitting dataset into train and test 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [5]:
sk_model = LogisticRegression()
sk_model.fit(x_train,y_train)

C:\Users\admin\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [27]:
#calculate the prediction on our test set
y_pred = sk_model.predict(x_test)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix , accuracy_score

In [8]:
class_names = iris.target_names
class_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [25]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [30]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

In [10]:
print(classification_report(y_test, y_pred, target_names=class_names))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [32]:
cm = confusion_matrix(y_test, y_pred)
print(confusion_matrix(y_test, y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [33]:
labels = ['setosa', 'versicolor', 'virginica']
pd.DataFrame(cm,index=labels,columns=labels)

setosa  versicolor  virginica
setosa          11           0          0
versicolor       0          13          0
virginica        0           0          6

In [16]:
# The accuracy = 1 : no wrong predictions 
# in our y_test : we have 11 setosa ,13 versicolor & 6 virginica
# The result of predictions is 11 out of 11 setosa , 13 out of 13 versicolor , 6 out of 6 virginica 

In [21]:
accuracy_score(y_test, y_pred) # all the predictions are right 

1.0